### ISSUE TITLE
Callsign lookup suggestions

### ISSUE THREAD

**Issue by dh1tw** [tzneal/ham-go#1]
Hey Todd, 

just a few comments which might help you:
- The best callsign lookup is IMHO [Clublog](https://clublog.org). They have a dedicated team maintaining the callsign/country database. They offer the [prefix and exception files](http://clublog.freshdesk.com/support/solutions/articles/54902-downloading-the-prefixes-and-exceptions-as-xml) for download. Alternatively, and more conveniently, you can also query their [API](http://clublog.freshdesk.com/support/solutions/articles/54904-how-to-query-club-log-for-dxcc-info) to resolve a callsign.

I'm operating the [DXHeat](https://dxheat.com) DX Cluster and found the quality of the Clublog data outstanding. 

I've also implemented a [callsign lookup in python](https://github.com/dh1tw/pyhamtools) among other things. I use this library to do all the lookups at DXHeat.com. The specific callsign lookup is [in this file](https://github.com/dh1tw/pyhamtools/blob/master/pyhamtools/callinfo.py).

BR Tobias

**Comment by dh1tw** [comment]
Country files are great for short term events, but they don’t support
historic records. Club log on the other hand has historic information about
almost any activity over the past 50 years. There are for example callsigns
which were allocated to different DXCCs over the years (e.g. K5K). Clublog
covers all those exceptions. IMHO for a logging application, Clublog
provides the most accurate data.

There is another pitfall with the countryfiles. Longitude comes with the
wrong sign. So east/West are flipped.

For precise locators and station information, the QRZ.com api is also good.
Although I think you need a subscription and the api is XML based.



Todd <notifications@github.com> schrieb am Do. 26. Apr. 2018 um 00:22:

**Comment by dh1tw** [comment]
Hey Todd,

just in case you haven't seen this project: https://github.com/rivo/tview

This might save you some work.

**Comment by tzneal** [comment]
@dh1tw Thanks, I haven't written much terminal UI stuff so I've enjoyed writing some low-level widgets.  I don't have any expectation of anyone besides me using this logger, but it's the only one I use so it fits my needs perfectly, and now with fldigi/wsjt-x logging :)
