### ISSUE TITLE
Make Rig management more flexible

### ISSUE THREAD

**Issue by dl1igc** [tzneal/ham-go#3]
Sometimes the connection to my rig changes (e.g. from ttyUSB0 to ttyUSB3). I think it would be interesting that the failure of a connection lets start the program (in the status bar it can mention "no-rig") and that a function is added to retry a connection with a given dev string

**Comment by tzneal** [comment]
@dl1igc Maybe a list of rigs to try, then default to no-rig with a warning?  I agree the behavior when you don't have a radio hooked up is very non-optimal.
